Frequently Asked Questions
McCambley/Prim-U pull request #19
Opened 2021-06-24 04:19 UTC by McCambley

Hey All, 
A little more convoluted of a pull request this time. A few sets of modifiers, a few sets of event listeners, a few setTimeouts, some array destructuring, lots of fun. Easier to see in action than read... I think: [Here's a demo](https://www.loom.com/share/07925cc9c1314d9e9d54f1bd915c4e4b).  The demo runs up against a 5 minute time limit so excuse my rambling at the end. 

Not a lot of content was available for this section on the brief. I pulled what I could from the website. 

I did my best to comment what's going in the code but if it needs explanation I'd love to hop on a call for a code review session. Feedback is definitely welcome and I think minor tweaks on transition and interval timing could be useful. 

Enjoy, let me know what you think, and thank you! 🎉

2021-06-24 10:37 UTC, Tongkorn commented on blocks/faq/faq.css
> +@media (min-width: 1440px) {
The font-size for most classes here should be a bit bigger for bigger screen.
Also, margin-bottom for `heading `class should be 80px. Currently it's 40px.
Overall, it's already looks so great! Just a spacing, pixel things.

2021-06-24 11:29 UTC, Tongkorn requested changes

2021-06-24 11:29 UTC, Tongkorn commented on blocks/faq/faq.css
> +@media (min-width: 1440px) {
The font-size for most classes here should be a bit bigger for bigger screen.
Also, margin-bottom for `heading `class should be 80px. Currently it's 40px.
Overall, it's already looks so great!

2021-06-24 11:29 UTC, Tongkorn commented on index.js
> +    let rev = 0;
Just an opinion, I don't quite understand what 'rev' stands for(at first glance). Using the full word here could be better. Like 'reversedItems', 'hiddenItems', etc. but I already know what it means so it's fine.

2021-06-25 01:59 UTC, larkceresin commented
@McCambley 
Main concern I have: on larger screens when you click show more: the additional questions/answers have one collum instead of the two that the previous bit had.
I think it might be easier to do a `display:none` that gets changed into `display: block` when opened, and could have that toggled on the sections like answers, and the additional FAQ that aren't originally visible. - wouldn't have to worry about the exact height of the content you're having in the section like you're switching from 0 to 300px for faq__answer on open.

You have two different grid template types defined in `.faq__subsection` at 1024px, you'll generally want one or the other.

2021-06-25 14:53 UTC, McCambley commented
Updated a few things: fonts a variable naming as per Jazzie's feedback, as well as moving the lower questions into two columns. This required a bit more array management on the JS side of things, hopefully the comments made sense. This section will be hard for a no-code person to come in an manage, which is a bummer. All the questions and answers have been pulled from the website, and they all repeat in the second section. I'm not sure what Prim-u will want where but that's a subject for a later date.

2021-06-25 21:44 UTC, larkceresin commented
I'm getting an issue on clicking 'show less' where the screen seems to shake a lot while it's closing.
(Tried to record it but the recording didn't pick it up, so might be my graphics rendering to me having issues) I'm getting it to happen at all screen widths, but also not 100% of the time. 

Aside from that I think it looks good!

2021-06-26 06:01 UTC, larkceresin requested changes
Couple style things .

2021-06-26 06:01 UTC, larkceresin commented on blocks/faq/faq.css
> +  margin-bottom: 40px;
This needs to change for 1024px where it gets to be 60px (this remains the same, and only secondary seems to be modifed at a different width - but only to 40 instead of 60px)

2021-06-26 06:01 UTC, larkceresin commented on blocks/faq/faq.css
> +    gap: 0, 60px;
Comma is making this style not being applied

2021-06-26 06:01 UTC, larkceresin commented on blocks/page/page.css
> +:root {
Should this technically be going on index.css rather than page.css since it's globar rather than for the page block?

2021-06-27 05:46 UTC, McCambley commented on blocks/page/page.css
> +:root {
100%

2021-06-27 05:58 UTC, McCambley commented on blocks/faq/faq.css
> +  margin-bottom: 40px;
Nice catch

2021-06-27 06:06 UTC, McCambley commented
Thanks for the feedback both of you, much appreciated. In hindsight I absolutely over complicated this. I think this was an easy place to use a grid layout... but I didn't think of that for some reason 🤦. Thanks for taking the time to look through it!

2021-06-27 15:02 UTC, larkceresin approved these changes

2021-06-27 15:02 UTC, merged